# Generated by Django 2.1.7 on 2019-03-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190307_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avata',
            new_name='avatar',
        ),
    ]
