# Generated by Django 2.1.7 on 2019-03-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190307_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.Book', verbose_name='评分的书籍'),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='评分者'),
        ),
    ]
