# Generated by Django 2.1.7 on 2019-03-07 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190307_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bandwidth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='kindle_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='collections',
            field=models.ManyToManyField(blank=True, null=True, related_name='collection_books', to='mainsite.Book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriptes',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscripte_books', to='mainsite.Book'),
        ),
    ]
