# Generated by Django 2.1.7 on 2019-03-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190308_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bandwidth',
            new_name='bandwidth_total',
        ),
        migrations.AddField(
            model_name='user',
            name='bandwidth_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
