# Generated by Django 2.1.7 on 2019-03-07 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190308_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kindle_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
