# Generated by Django 2.1.7 on 2019-03-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_bandwidth_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bandwidth_remain',
            field=models.IntegerField(default=0),
        ),
    ]
