# Generated by Django 2.1.7 on 2019-03-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='作者名')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='EpubVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='books')),
            ],
        ),
        migrations.CreateModel(
            name='ImageWithThumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_time', models.DateTimeField(verbose_name='上传时间')),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('thumb_image', models.ImageField(blank=True, upload_to='img')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
        migrations.CreateModel(
            name='MobiVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='books')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '书籍', 'verbose_name_plural': '书籍'},
        ),
        migrations.AddField(
            model_name='book',
            name='bangumi_site_path',
            field=models.IntegerField(default=0, verbose_name='Bangumi网站id'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_id',
            field=models.IntegerField(default=-1, verbose_name='使用哪张图'),
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='book',
            name='mediaarts_site_path',
            field=models.IntegerField(default=0, verbose_name='メディア芸術データベース网站id'),
        ),
        migrations.AddField(
            model_name='book',
            name='sakuhindb_path',
            field=models.TextField(default=0, verbose_name='sakuhindb网站路径'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_chinese',
            field=models.CharField(blank=True, max_length=255, verbose_name='中文名'),
        ),
        migrations.AddField(
            model_name='book',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='书名'),
        ),
        migrations.AddField(
            model_name='mobivolume',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.Book'),
        ),
        migrations.AddField(
            model_name='epubvolume',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.Book'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, to='mainsite.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='covers',
            field=models.ManyToManyField(blank=True, to='mainsite.ImageWithThumb', verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainsite.Tag'),
        ),
    ]
