# Generated by Django 2.1.7 on 2019-03-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_book_cover_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(to='mainsite.Book')),
            ],
        ),
    ]
