# Generated by Django 2.1.7 on 2019-03-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20190304_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='epubvolume',
            name='name',
            field=models.CharField(default='默认', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobivolume',
            name='name',
            field=models.CharField(default='默认', max_length=255),
            preserve_default=False,
        ),
    ]
