# Generated by Django 2.1.7 on 2019-03-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_homepagegroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagegroup',
            options={'verbose_name': '首页分组', 'verbose_name_plural': '首页分组'},
        ),
    ]
