# Generated by Django 2.1.7 on 2019-03-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20190304_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='epubvolume',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
