# Generated by Django 2.1.7 on 2019-03-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20190307_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewiththumb',
            name='type',
            field=models.CharField(default='image', max_length=20),
        ),
    ]
