# Generated by Django 2.1.7 on 2019-03-03 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_mobivolume_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='epubvolume',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.VolumeType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobivolume',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.VolumeType'),
            preserve_default=False,
        ),
    ]
