# Generated by Django 2.1.7 on 2019-03-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_imagewiththumb_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
