# Generated by Django 2.1.7 on 2019-03-04 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20190304_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to='books')),
                ('epub_file', models.FileField(upload_to='books')),
                ('mobi_file', models.FileField(upload_to='books')),
                ('mobi_push_file', models.FileField(upload_to='books')),
                ('name', models.CharField(max_length=255)),
                ('show', models.BooleanField(default=True)),
                ('index', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.Book')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.VolumeType')),
            ],
        ),
        migrations.RemoveField(
            model_name='epubvolume',
            name='book',
        ),
        migrations.RemoveField(
            model_name='epubvolume',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mobivolume',
            name='book',
        ),
        migrations.RemoveField(
            model_name='mobivolume',
            name='type',
        ),
        migrations.DeleteModel(
            name='EpubVolume',
        ),
        migrations.DeleteModel(
            name='MobiVolume',
        ),
    ]
