# Generated by Django 2.1.7 on 2019-03-04 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20190304_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookConvertQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='volume',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.Book', verbose_name='关联书籍'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='epub_file',
            field=models.FileField(blank=True, null=True, upload_to='books', verbose_name='epub文件'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='index',
            field=models.IntegerField(default=0, verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='mobi_file',
            field=models.FileField(blank=True, null=True, upload_to='books', verbose_name='mobi文件'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='mobi_push_file',
            field=models.FileField(blank=True, null=True, upload_to='books', verbose_name='mobi推送文件'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(max_length=255, verbose_name='卷名'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='show',
            field=models.BooleanField(default=True, verbose_name='显示'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.VolumeType', verbose_name='卷类型'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='zip_file',
            field=models.FileField(upload_to='books', verbose_name='zip文件'),
        ),
        migrations.AddField(
            model_name='ebookconvertqueue',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Volume'),
        ),
    ]
