# Generated by Django 2.1.7 on 2019-03-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20190304_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='need_convert',
            field=models.BooleanField(default=True, verbose_name='是否需要转换'),
        ),
    ]
