# Generated by Django 2.1.7 on 2019-03-04 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_volume_need_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookconvertqueue',
            name='epub_ok',
            field=models.BooleanField(default=False, verbose_name='epub转换完成'),
        ),
        migrations.AddField(
            model_name='ebookconvertqueue',
            name='mobi_ok',
            field=models.BooleanField(default=False, verbose_name='mobi转换完成'),
        ),
        migrations.AddField(
            model_name='ebookconvertqueue',
            name='mobi_push_ok',
            field=models.BooleanField(default=False, verbose_name='mobi推送版转换完成'),
        ),
        migrations.AlterField(
            model_name='ebookconvertqueue',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Volume', verbose_name='待转换书籍'),
        ),
    ]
