# Generated by Django 2.1.7 on 2019-03-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20190304_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebookconvertqueue',
            options={'verbose_name': '格式待转换队列', 'verbose_name_plural': '格式待转换队列'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': '书籍', 'verbose_name_plural': '卷信息'},
        ),
        migrations.AddField(
            model_name='ebookconvertqueue',
            name='status',
            field=models.CharField(default='pending', max_length=100, verbose_name='状态'),
        ),
    ]
