# Generated by Django 2.1.7 on 2019-03-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20190304_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookConvertOver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epub_ok', models.BooleanField(default=False, verbose_name='epub转换完成')),
                ('mobi_ok', models.BooleanField(default=False, verbose_name='mobi转换完成')),
                ('mobi_push_ok', models.BooleanField(default=False, verbose_name='mobi推送版转换完成')),
                ('status', models.CharField(default='pending', max_length=100, verbose_name='状态')),
            ],
        ),
        migrations.AlterField(
            model_name='volume',
            name='epub_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='epub文件'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='mobi_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='mobi文件'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='mobi_push_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='mobi推送文件'),
        ),
        migrations.AddField(
            model_name='ebookconvertover',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Volume', verbose_name='待转换书籍'),
        ),
    ]
